// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: services/treasury-services/treasury-service/proto/treasury_service.proto

package treasury

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	// Service is fully operational
	ServiceStatus_HEALTHY ServiceStatus = 0
	// Service is operational but with non-critical issues
	ServiceStatus_DEGRADED ServiceStatus = 1
	// Service is not operational
	ServiceStatus_UNHEALTHY ServiceStatus = 2
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "DEGRADED",
		2: "UNHEALTHY",
	}
	ServiceStatus_value = map[string]int32{
		"HEALTHY":   0,
		"DEGRADED":  1,
		"UNHEALTHY": 2,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{0}
}

type DependencyType int32

const (
	DependencyType_DATABASE      DependencyType = 0
	DependencyType_CACHE         DependencyType = 1
	DependencyType_MESSAGE_QUEUE DependencyType = 2
	DependencyType_GRPC_SERVICE  DependencyType = 3
	DependencyType_HTTP_SERVICE  DependencyType = 4
	DependencyType_STORAGE       DependencyType = 5
	DependencyType_OTHER         DependencyType = 6
)

// Enum value maps for DependencyType.
var (
	DependencyType_name = map[int32]string{
		0: "DATABASE",
		1: "CACHE",
		2: "MESSAGE_QUEUE",
		3: "GRPC_SERVICE",
		4: "HTTP_SERVICE",
		5: "STORAGE",
		6: "OTHER",
	}
	DependencyType_value = map[string]int32{
		"DATABASE":      0,
		"CACHE":         1,
		"MESSAGE_QUEUE": 2,
		"GRPC_SERVICE":  3,
		"HTTP_SERVICE":  4,
		"STORAGE":       5,
		"OTHER":         6,
	}
)

func (x DependencyType) Enum() *DependencyType {
	p := new(DependencyType)
	*p = x
	return p
}

func (x DependencyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DependencyType) Descriptor() protoreflect.EnumDescriptor {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[1].Descriptor()
}

func (DependencyType) Type() protoreflect.EnumType {
	return &file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[1]
}

func (x DependencyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DependencyType.Descriptor instead.
func (DependencyType) EnumDescriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{1}
}

type CurrencyStatus int32

const (
	CurrencyStatus_CURRENCY_STATUS_UNSPECIFIED CurrencyStatus = 0
	CurrencyStatus_CURRENCY_STATUS_ACTIVE      CurrencyStatus = 1
	CurrencyStatus_CURRENCY_STATUS_INACTIVE    CurrencyStatus = 2
	CurrencyStatus_CURRENCY_STATUS_DEPRECATED  CurrencyStatus = 3
	CurrencyStatus_CURRENCY_STATUS_DELETED     CurrencyStatus = 4
)

// Enum value maps for CurrencyStatus.
var (
	CurrencyStatus_name = map[int32]string{
		0: "CURRENCY_STATUS_UNSPECIFIED",
		1: "CURRENCY_STATUS_ACTIVE",
		2: "CURRENCY_STATUS_INACTIVE",
		3: "CURRENCY_STATUS_DEPRECATED",
		4: "CURRENCY_STATUS_DELETED",
	}
	CurrencyStatus_value = map[string]int32{
		"CURRENCY_STATUS_UNSPECIFIED": 0,
		"CURRENCY_STATUS_ACTIVE":      1,
		"CURRENCY_STATUS_INACTIVE":    2,
		"CURRENCY_STATUS_DEPRECATED":  3,
		"CURRENCY_STATUS_DELETED":     4,
	}
)

func (x CurrencyStatus) Enum() *CurrencyStatus {
	p := new(CurrencyStatus)
	*p = x
	return p
}

func (x CurrencyStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CurrencyStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[2].Descriptor()
}

func (CurrencyStatus) Type() protoreflect.EnumType {
	return &file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes[2]
}

func (x CurrencyStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CurrencyStatus.Descriptor instead.
func (CurrencyStatus) EnumDescriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{2}
}

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{0}
}

type ManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service identity
	Identity *ServiceIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Build information
	BuildInfo *BuildInfo `protobuf:"bytes,2,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	// Runtime information
	RuntimeInfo *RuntimeInfo `protobuf:"bytes,3,opt,name=runtime_info,json=runtimeInfo,proto3" json:"runtime_info,omitempty"`
	// Service metadata
	Metadata *ServiceMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Service capabilities
	Capabilities  *ServiceCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetIdentity() *ServiceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ManifestResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *ManifestResponse) GetRuntimeInfo() *RuntimeInfo {
	if x != nil {
		return x.RuntimeInfo
	}
	return nil
}

func (x *ManifestResponse) GetMetadata() *ServiceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ManifestResponse) GetCapabilities() *ServiceCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServiceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Service name (e.g., "treasury-service")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                         // Semantic version (e.g., "1.2.3")
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // API version (e.g., "v1")
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // Brief service description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdentity) Reset() {
	*x = ServiceIdentity{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdentity) ProtoMessage() {}

func (x *ServiceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdentity.ProtoReflect.Descriptor instead.
func (*ServiceIdentity) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceIdentity) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ServiceIdentity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // Git commit SHA
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`                           // Git branch name
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`    // RFC3339 timestamp
	Builder       string                 `protobuf:"bytes,4,opt,name=builder,proto3" json:"builder,omitempty"`                         // CI system or user
	IsDirty       bool                   `protobuf:"varint,5,opt,name=is_dirty,json=isDirty,proto3" json:"is_dirty,omitempty"`         // Whether build had uncommitted changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{3}
}

func (x *BuildInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BuildInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *BuildInfo) GetBuilder() string {
	if x != nil {
		return x.Builder
	}
	return ""
}

func (x *BuildInfo) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`           // Unique instance identifier
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // Host machine name
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`              // RFC3339 timestamp
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`                           // Environment (dev/staging/prod)
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                     // Deployment region/zone
	UptimeSeconds int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // Seconds since start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RuntimeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RuntimeInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RuntimeInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RuntimeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RuntimeInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ServiceMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Owner            string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                                                                             // Team or owner email
	RepositoryUrl    string                 `protobuf:"bytes,2,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`                                        // Source code repository
	DocumentationUrl string                 `protobuf:"bytes,3,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`                               // Service documentation
	SupportContact   string                 `protobuf:"bytes,4,opt,name=support_contact,json=supportContact,proto3" json:"support_contact,omitempty"`                                     // Support contact info
	Labels           map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional labels/tags
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceMetadata) Reset() {
	*x = ServiceMetadata{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetadata) ProtoMessage() {}

func (x *ServiceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetadata.ProtoReflect.Descriptor instead.
func (*ServiceMetadata) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ServiceMetadata) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *ServiceMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *ServiceMetadata) GetSupportContact() string {
	if x != nil {
		return x.SupportContact
	}
	return ""
}

func (x *ServiceMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ServiceCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersions   []string               `protobuf:"bytes,1,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"` // Supported API versions
	Protocols     []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`                        // Supported protocols (grpc, http)
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`                          // Enabled feature flags
	Dependencies  []*ServiceDependency   `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                  // Required services
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCapabilities) Reset() {
	*x = ServiceCapabilities{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCapabilities) ProtoMessage() {}

func (x *ServiceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCapabilities.ProtoReflect.Descriptor instead.
func (*ServiceCapabilities) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceCapabilities) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *ServiceCapabilities) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *ServiceCapabilities) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ServiceCapabilities) GetDependencies() []*ServiceDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ServiceDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                // Dependency service name
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                          // Required version (semver range)
	IsOptional    bool                   `protobuf:"varint,3,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"` // Whether dependency is optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDependency) Reset() {
	*x = ServiceDependency{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDependency) ProtoMessage() {}

func (x *ServiceDependency) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDependency.ProtoReflect.Descriptor instead.
func (*ServiceDependency) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceDependency) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{8}
}

type LivenessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall liveness status
	Status ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=treasury.ServiceStatus" json:"status,omitempty"`
	// Human-readable message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Component readiness checks
	Checks []*ComponentCheck `protobuf:"bytes,3,rep,name=checks,proto3" json:"checks,omitempty"`
	// Timestamp of the check
	CheckedAt     string `protobuf:"bytes,4,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"` // RFC3339 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{9}
}

func (x *LivenessResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_HEALTHY
}

func (x *LivenessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LivenessResponse) GetChecks() []*ComponentCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *LivenessResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

type HealthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Include detailed dependency info
	IncludeDetails bool `protobuf:"varint,1,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	// Check specific dependencies only
	DependencyFilter []string `protobuf:"bytes,2,rep,name=dependency_filter,json=dependencyFilter,proto3" json:"dependency_filter,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{10}
}

func (x *HealthRequest) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

func (x *HealthRequest) GetDependencyFilter() []string {
	if x != nil {
		return x.DependencyFilter
	}
	return nil
}

type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status
	Status ServiceStatus `protobuf:"varint,1,opt,name=status,proto3,enum=treasury.ServiceStatus" json:"status,omitempty"`
	// Human-readable message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Service liveness (internal readiness)
	Liveness *LivenessInfo `protobuf:"bytes,3,opt,name=liveness,proto3" json:"liveness,omitempty"`
	// Dependency health checks
	Dependencies []*DependencyHealth `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	// Timestamp of the check
	CheckedAt string `protobuf:"bytes,5,opt,name=checked_at,json=checkedAt,proto3" json:"checked_at,omitempty"` // RFC3339 format
	// Time taken to perform all checks (milliseconds)
	CheckDurationMs int64 `protobuf:"varint,6,opt,name=check_duration_ms,json=checkDurationMs,proto3" json:"check_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_HEALTHY
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HealthResponse) GetLiveness() *LivenessInfo {
	if x != nil {
		return x.Liveness
	}
	return nil
}

func (x *HealthResponse) GetDependencies() []*DependencyHealth {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *HealthResponse) GetCheckedAt() string {
	if x != nil {
		return x.CheckedAt
	}
	return ""
}

func (x *HealthResponse) GetCheckDurationMs() int64 {
	if x != nil {
		return x.CheckDurationMs
	}
	return 0
}

type ComponentCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Component name (e.g., "config", "database_pool", "cache")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Component status
	Ready bool `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	// Optional message
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentCheck) Reset() {
	*x = ComponentCheck{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentCheck) ProtoMessage() {}

func (x *ComponentCheck) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentCheck.ProtoReflect.Descriptor instead.
func (*ComponentCheck) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{12}
}

func (x *ComponentCheck) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentCheck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ComponentCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LivenessInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Is service ready to accept traffic
	IsAlive bool `protobuf:"varint,1,opt,name=is_alive,json=isAlive,proto3" json:"is_alive,omitempty"`
	// Service initialization status
	ConfigLoaded bool `protobuf:"varint,2,opt,name=config_loaded,json=configLoaded,proto3" json:"config_loaded,omitempty"`
	PoolsReady   bool `protobuf:"varint,3,opt,name=pools_ready,json=poolsReady,proto3" json:"pools_ready,omitempty"`
	CacheWarmed  bool `protobuf:"varint,4,opt,name=cache_warmed,json=cacheWarmed,proto3" json:"cache_warmed,omitempty"`
	// Custom readiness checks
	Components    []*ComponentCheck `protobuf:"bytes,5,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessInfo) Reset() {
	*x = LivenessInfo{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessInfo) ProtoMessage() {}

func (x *LivenessInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessInfo.ProtoReflect.Descriptor instead.
func (*LivenessInfo) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{13}
}

func (x *LivenessInfo) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *LivenessInfo) GetConfigLoaded() bool {
	if x != nil {
		return x.ConfigLoaded
	}
	return false
}

func (x *LivenessInfo) GetPoolsReady() bool {
	if x != nil {
		return x.PoolsReady
	}
	return false
}

func (x *LivenessInfo) GetCacheWarmed() bool {
	if x != nil {
		return x.CacheWarmed
	}
	return false
}

func (x *LivenessInfo) GetComponents() []*ComponentCheck {
	if x != nil {
		return x.Components
	}
	return nil
}

type DependencyHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dependency name (e.g., "postgres", "redis", "user-service")
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Dependency type
	Type DependencyType `protobuf:"varint,2,opt,name=type,proto3,enum=treasury.DependencyType" json:"type,omitempty"`
	// Health status
	Status ServiceStatus `protobuf:"varint,3,opt,name=status,proto3,enum=treasury.ServiceStatus" json:"status,omitempty"`
	// Is this dependency critical for service operation
	IsCritical bool `protobuf:"varint,4,opt,name=is_critical,json=isCritical,proto3" json:"is_critical,omitempty"`
	// Human-readable status message
	Message string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	// Configuration details (non-sensitive)
	Config *DependencyConfig `protobuf:"bytes,6,opt,name=config,proto3" json:"config,omitempty"`
	// Last successful check timestamp
	LastSuccess string `protobuf:"bytes,7,opt,name=last_success,json=lastSuccess,proto3" json:"last_success,omitempty"` // RFC3339 format
	// Last check timestamp
	LastCheck string `protobuf:"bytes,8,opt,name=last_check,json=lastCheck,proto3" json:"last_check,omitempty"` // RFC3339 format
	// Response time of health check (milliseconds)
	ResponseTimeMs int64 `protobuf:"varint,9,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	// Error details if unhealthy
	Error         string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyHealth) Reset() {
	*x = DependencyHealth{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyHealth) ProtoMessage() {}

func (x *DependencyHealth) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyHealth.ProtoReflect.Descriptor instead.
func (*DependencyHealth) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{14}
}

func (x *DependencyHealth) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DependencyHealth) GetType() DependencyType {
	if x != nil {
		return x.Type
	}
	return DependencyType_DATABASE
}

func (x *DependencyHealth) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_HEALTHY
}

func (x *DependencyHealth) GetIsCritical() bool {
	if x != nil {
		return x.IsCritical
	}
	return false
}

func (x *DependencyHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DependencyHealth) GetConfig() *DependencyConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *DependencyHealth) GetLastSuccess() string {
	if x != nil {
		return x.LastSuccess
	}
	return ""
}

func (x *DependencyHealth) GetLastCheck() string {
	if x != nil {
		return x.LastCheck
	}
	return ""
}

func (x *DependencyHealth) GetResponseTimeMs() int64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *DependencyHealth) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DependencyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Connection information (non-sensitive)
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Port     int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol string `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // e.g., "grpc", "http", "postgres"
	// Database/schema/topic information
	DatabaseName string `protobuf:"bytes,4,opt,name=database_name,json=databaseName,proto3" json:"database_name,omitempty"`
	SchemaName   string `protobuf:"bytes,5,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	TopicName    string `protobuf:"bytes,6,opt,name=topic_name,json=topicName,proto3" json:"topic_name,omitempty"`
	// Connection pool information
	PoolInfo *ConnectionPoolInfo `protobuf:"bytes,7,opt,name=pool_info,json=poolInfo,proto3" json:"pool_info,omitempty"`
	// Service version if applicable
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Additional metadata
	Metadata      map[string]string `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DependencyConfig) Reset() {
	*x = DependencyConfig{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DependencyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DependencyConfig) ProtoMessage() {}

func (x *DependencyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DependencyConfig.ProtoReflect.Descriptor instead.
func (*DependencyConfig) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{15}
}

func (x *DependencyConfig) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *DependencyConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DependencyConfig) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DependencyConfig) GetDatabaseName() string {
	if x != nil {
		return x.DatabaseName
	}
	return ""
}

func (x *DependencyConfig) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *DependencyConfig) GetTopicName() string {
	if x != nil {
		return x.TopicName
	}
	return ""
}

func (x *DependencyConfig) GetPoolInfo() *ConnectionPoolInfo {
	if x != nil {
		return x.PoolInfo
	}
	return nil
}

func (x *DependencyConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DependencyConfig) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ConnectionPoolInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MaxConnections    int32                  `protobuf:"varint,1,opt,name=max_connections,json=maxConnections,proto3" json:"max_connections,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	IdleConnections   int32                  `protobuf:"varint,3,opt,name=idle_connections,json=idleConnections,proto3" json:"idle_connections,omitempty"`
	WaitCount         int32                  `protobuf:"varint,4,opt,name=wait_count,json=waitCount,proto3" json:"wait_count,omitempty"`
	WaitDurationMs    int64                  `protobuf:"varint,5,opt,name=wait_duration_ms,json=waitDurationMs,proto3" json:"wait_duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConnectionPoolInfo) Reset() {
	*x = ConnectionPoolInfo{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionPoolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionPoolInfo) ProtoMessage() {}

func (x *ConnectionPoolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionPoolInfo.ProtoReflect.Descriptor instead.
func (*ConnectionPoolInfo) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{16}
}

func (x *ConnectionPoolInfo) GetMaxConnections() int32 {
	if x != nil {
		return x.MaxConnections
	}
	return 0
}

func (x *ConnectionPoolInfo) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ConnectionPoolInfo) GetIdleConnections() int32 {
	if x != nil {
		return x.IdleConnections
	}
	return 0
}

func (x *ConnectionPoolInfo) GetWaitCount() int32 {
	if x != nil {
		return x.WaitCount
	}
	return 0
}

func (x *ConnectionPoolInfo) GetWaitDurationMs() int64 {
	if x != nil {
		return x.WaitDurationMs
	}
	return 0
}

// Currency represents an ISO 4217 compliant currency
type Currency struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // UUID
	Code           string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                           // ISO 4217 code (USD, EUR)
	NumericCode    string                 `protobuf:"bytes,3,opt,name=numeric_code,json=numericCode,proto3" json:"numeric_code,omitempty"`          // ISO 4217 numeric code
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                           // Official name
	MinorUnits     int32                  `protobuf:"varint,5,opt,name=minor_units,json=minorUnits,proto3" json:"minor_units,omitempty"`            // Decimal places
	Symbol         string                 `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`                                       // Currency symbol
	SymbolPosition string                 `protobuf:"bytes,7,opt,name=symbol_position,json=symbolPosition,proto3" json:"symbol_position,omitempty"` // before/after
	CountryCodes   []string               `protobuf:"bytes,8,rep,name=country_codes,json=countryCodes,proto3" json:"country_codes,omitempty"`       // ISO 3166 codes
	IsActive       bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                  // Active status
	IsCrypto       bool                   `protobuf:"varint,10,opt,name=is_crypto,json=isCrypto,proto3" json:"is_crypto,omitempty"`                 // Cryptocurrency flag
	Status         CurrencyStatus         `protobuf:"varint,11,opt,name=status,proto3,enum=treasury.CurrencyStatus" json:"status,omitempty"`        // Current status
	ActivatedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=activated_at,json=activatedAt,proto3" json:"activated_at,omitempty"`
	DeactivatedAt  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=deactivated_at,json=deactivatedAt,proto3" json:"deactivated_at,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,16,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,17,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Version        int32                  `protobuf:"varint,18,opt,name=version,proto3" json:"version,omitempty"` // Optimistic locking
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{17}
}

func (x *Currency) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Currency) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Currency) GetNumericCode() string {
	if x != nil {
		return x.NumericCode
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetMinorUnits() int32 {
	if x != nil {
		return x.MinorUnits
	}
	return 0
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetSymbolPosition() string {
	if x != nil {
		return x.SymbolPosition
	}
	return ""
}

func (x *Currency) GetCountryCodes() []string {
	if x != nil {
		return x.CountryCodes
	}
	return nil
}

func (x *Currency) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Currency) GetIsCrypto() bool {
	if x != nil {
		return x.IsCrypto
	}
	return false
}

func (x *Currency) GetStatus() CurrencyStatus {
	if x != nil {
		return x.Status
	}
	return CurrencyStatus_CURRENCY_STATUS_UNSPECIFIED
}

func (x *Currency) GetActivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ActivatedAt
	}
	return nil
}

func (x *Currency) GetDeactivatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeactivatedAt
	}
	return nil
}

func (x *Currency) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Currency) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Currency) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Currency) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Currency) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Request/Response messages
type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                  // Required
	NumericCode   string                 `protobuf:"bytes,2,opt,name=numeric_code,json=numericCode,proto3" json:"numeric_code,omitempty"` // Optional
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                                  // Required
	MinorUnits    int32                  `protobuf:"varint,4,opt,name=minor_units,json=minorUnits,proto3" json:"minor_units,omitempty"`   // Default 2
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CountryCodes  []string               `protobuf:"bytes,6,rep,name=country_codes,json=countryCodes,proto3" json:"country_codes,omitempty"`
	IsCrypto      bool                   `protobuf:"varint,7,opt,name=is_crypto,json=isCrypto,proto3" json:"is_crypto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{18}
}

func (x *CreateCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateCurrencyRequest) GetNumericCode() string {
	if x != nil {
		return x.NumericCode
	}
	return ""
}

func (x *CreateCurrencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCurrencyRequest) GetMinorUnits() int32 {
	if x != nil {
		return x.MinorUnits
	}
	return 0
}

func (x *CreateCurrencyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateCurrencyRequest) GetCountryCodes() []string {
	if x != nil {
		return x.CountryCodes
	}
	return nil
}

func (x *CreateCurrencyRequest) GetIsCrypto() bool {
	if x != nil {
		return x.IsCrypto
	}
	return false
}

type CreateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyResponse) Reset() {
	*x = CreateCurrencyResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyResponse) ProtoMessage() {}

func (x *CreateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*CreateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{19}
}

func (x *CreateCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type GetCurrencyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Identifier:
	//
	//	*GetCurrencyRequest_Code
	//	*GetCurrencyRequest_NumericCode
	//	*GetCurrencyRequest_Id
	Identifier    isGetCurrencyRequest_Identifier `protobuf_oneof:"identifier"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyRequest) Reset() {
	*x = GetCurrencyRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyRequest) ProtoMessage() {}

func (x *GetCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{20}
}

func (x *GetCurrencyRequest) GetIdentifier() isGetCurrencyRequest_Identifier {
	if x != nil {
		return x.Identifier
	}
	return nil
}

func (x *GetCurrencyRequest) GetCode() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCurrencyRequest_Code); ok {
			return x.Code
		}
	}
	return ""
}

func (x *GetCurrencyRequest) GetNumericCode() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCurrencyRequest_NumericCode); ok {
			return x.NumericCode
		}
	}
	return ""
}

func (x *GetCurrencyRequest) GetId() string {
	if x != nil {
		if x, ok := x.Identifier.(*GetCurrencyRequest_Id); ok {
			return x.Id
		}
	}
	return ""
}

type isGetCurrencyRequest_Identifier interface {
	isGetCurrencyRequest_Identifier()
}

type GetCurrencyRequest_Code struct {
	Code string `protobuf:"bytes,1,opt,name=code,proto3,oneof"` // Primary lookup
}

type GetCurrencyRequest_NumericCode struct {
	NumericCode string `protobuf:"bytes,2,opt,name=numeric_code,json=numericCode,proto3,oneof"` // Alternative lookup
}

type GetCurrencyRequest_Id struct {
	Id string `protobuf:"bytes,3,opt,name=id,proto3,oneof"` // UUID lookup
}

func (*GetCurrencyRequest_Code) isGetCurrencyRequest_Identifier() {}

func (*GetCurrencyRequest_NumericCode) isGetCurrencyRequest_Identifier() {}

func (*GetCurrencyRequest_Id) isGetCurrencyRequest_Identifier() {}

type GetCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyResponse) Reset() {
	*x = GetCurrencyResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyResponse) ProtoMessage() {}

func (x *GetCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{21}
}

func (x *GetCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type UpdateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                               // Required (identifies currency)
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"` // Fields to update
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	MinorUnits    int32                  `protobuf:"varint,4,opt,name=minor_units,json=minorUnits,proto3" json:"minor_units,omitempty"`
	Symbol        string                 `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol,omitempty"`
	CountryCodes  []string               `protobuf:"bytes,6,rep,name=country_codes,json=countryCodes,proto3" json:"country_codes,omitempty"`
	Status        CurrencyStatus         `protobuf:"varint,7,opt,name=status,proto3,enum=treasury.CurrencyStatus" json:"status,omitempty"`
	Version       int32                  `protobuf:"varint,8,opt,name=version,proto3" json:"version,omitempty"` // For optimistic locking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyRequest) Reset() {
	*x = UpdateCurrencyRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyRequest) ProtoMessage() {}

func (x *UpdateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateCurrencyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetMinorUnits() int32 {
	if x != nil {
		return x.MinorUnits
	}
	return 0
}

func (x *UpdateCurrencyRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *UpdateCurrencyRequest) GetCountryCodes() []string {
	if x != nil {
		return x.CountryCodes
	}
	return nil
}

func (x *UpdateCurrencyRequest) GetStatus() CurrencyStatus {
	if x != nil {
		return x.Status
	}
	return CurrencyStatus_CURRENCY_STATUS_UNSPECIFIED
}

func (x *UpdateCurrencyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currency      *Currency              `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyResponse) Reset() {
	*x = UpdateCurrencyResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyResponse) ProtoMessage() {}

func (x *UpdateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type DeactivateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`                                   // Required
	Status        CurrencyStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=treasury.CurrencyStatus" json:"status,omitempty"` // New status (inactive/deprecated/deleted)
	UpdatedBy     string                 `protobuf:"bytes,3,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`        // User making the change
	Version       int32                  `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`                            // For optimistic locking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateCurrencyRequest) Reset() {
	*x = DeactivateCurrencyRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateCurrencyRequest) ProtoMessage() {}

func (x *DeactivateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*DeactivateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{24}
}

func (x *DeactivateCurrencyRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DeactivateCurrencyRequest) GetStatus() CurrencyStatus {
	if x != nil {
		return x.Status
	}
	return CurrencyStatus_CURRENCY_STATUS_UNSPECIFIED
}

func (x *DeactivateCurrencyRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *DeactivateCurrencyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeactivateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Currency      *Currency              `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"` // Updated currency
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeactivateCurrencyResponse) Reset() {
	*x = DeactivateCurrencyResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeactivateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeactivateCurrencyResponse) ProtoMessage() {}

func (x *DeactivateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeactivateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*DeactivateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{25}
}

func (x *DeactivateCurrencyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeactivateCurrencyResponse) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

type ListCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CurrencyStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=treasury.CurrencyStatus" json:"status,omitempty"` // Filter by status
	IsActive      bool                   `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`          // Filter by active flag
	IsCrypto      bool                   `protobuf:"varint,3,opt,name=is_crypto,json=isCrypto,proto3" json:"is_crypto,omitempty"`          // Filter cryptocurrencies
	CountryCode   string                 `protobuf:"bytes,4,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`  // Filter by country
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // Pagination
	PageToken     string                 `protobuf:"bytes,6,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`        // Pagination token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesRequest) Reset() {
	*x = ListCurrenciesRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesRequest) ProtoMessage() {}

func (x *ListCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*ListCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{26}
}

func (x *ListCurrenciesRequest) GetStatus() CurrencyStatus {
	if x != nil {
		return x.Status
	}
	return CurrencyStatus_CURRENCY_STATUS_UNSPECIFIED
}

func (x *ListCurrenciesRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *ListCurrenciesRequest) GetIsCrypto() bool {
	if x != nil {
		return x.IsCrypto
	}
	return false
}

func (x *ListCurrenciesRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *ListCurrenciesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCurrenciesRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Currencies    []*Currency            `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrenciesResponse) Reset() {
	*x = ListCurrenciesResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrenciesResponse) ProtoMessage() {}

func (x *ListCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*ListCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{27}
}

func (x *ListCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *ListCurrenciesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCurrenciesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type BulkCreateCurrenciesRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Currencies     []*CreateCurrencyRequest `protobuf:"bytes,1,rep,name=currencies,proto3" json:"currencies,omitempty"`
	SkipDuplicates bool                     `protobuf:"varint,2,opt,name=skip_duplicates,json=skipDuplicates,proto3" json:"skip_duplicates,omitempty"` // Skip existing currencies
	UpdateExisting bool                     `protobuf:"varint,3,opt,name=update_existing,json=updateExisting,proto3" json:"update_existing,omitempty"` // Update if exists
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BulkCreateCurrenciesRequest) Reset() {
	*x = BulkCreateCurrenciesRequest{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateCurrenciesRequest) ProtoMessage() {}

func (x *BulkCreateCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*BulkCreateCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{28}
}

func (x *BulkCreateCurrenciesRequest) GetCurrencies() []*CreateCurrencyRequest {
	if x != nil {
		return x.Currencies
	}
	return nil
}

func (x *BulkCreateCurrenciesRequest) GetSkipDuplicates() bool {
	if x != nil {
		return x.SkipDuplicates
	}
	return false
}

func (x *BulkCreateCurrenciesRequest) GetUpdateExisting() bool {
	if x != nil {
		return x.UpdateExisting
	}
	return false
}

type BulkCreateCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedCount  int32                  `protobuf:"varint,1,opt,name=created_count,json=createdCount,proto3" json:"created_count,omitempty"`
	UpdatedCount  int32                  `protobuf:"varint,2,opt,name=updated_count,json=updatedCount,proto3" json:"updated_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,3,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	Errors        []string               `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkCreateCurrenciesResponse) Reset() {
	*x = BulkCreateCurrenciesResponse{}
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkCreateCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkCreateCurrenciesResponse) ProtoMessage() {}

func (x *BulkCreateCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkCreateCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*BulkCreateCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP(), []int{29}
}

func (x *BulkCreateCurrenciesResponse) GetCreatedCount() int32 {
	if x != nil {
		return x.CreatedCount
	}
	return 0
}

func (x *BulkCreateCurrenciesResponse) GetUpdatedCount() int32 {
	if x != nil {
		return x.UpdatedCount
	}
	return 0
}

func (x *BulkCreateCurrenciesResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *BulkCreateCurrenciesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_services_treasury_services_treasury_service_proto_treasury_service_proto protoreflect.FileDescriptor

const file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDesc = "" +
	"\n" +
	"Hservices/treasury-services/treasury-service/proto/treasury_service.proto\x12\btreasury\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\x11\n" +
	"\x0fManifestRequest\"\xb1\x02\n" +
	"\x10ManifestResponse\x125\n" +
	"\bidentity\x18\x01 \x01(\v2\x19.treasury.ServiceIdentityR\bidentity\x122\n" +
	"\n" +
	"build_info\x18\x02 \x01(\v2\x13.treasury.BuildInfoR\tbuildInfo\x128\n" +
	"\fruntime_info\x18\x03 \x01(\v2\x15.treasury.RuntimeInfoR\vruntimeInfo\x125\n" +
	"\bmetadata\x18\x04 \x01(\v2\x19.treasury.ServiceMetadataR\bmetadata\x12A\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1d.treasury.ServiceCapabilitiesR\fcapabilities\"\x82\x01\n" +
	"\x0fServiceIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x98\x01\n" +
	"\tBuildInfo\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x12\x18\n" +
	"\abuilder\x18\x04 \x01(\tR\abuilder\x12\x19\n" +
	"\bis_dirty\x18\x05 \x01(\bR\aisDirty\"\xca\x01\n" +
	"\vRuntimeInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\"\x9e\x02\n" +
	"\x0fServiceMetadata\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0erepository_url\x18\x02 \x01(\tR\rrepositoryUrl\x12+\n" +
	"\x11documentation_url\x18\x03 \x01(\tR\x10documentationUrl\x12'\n" +
	"\x0fsupport_contact\x18\x04 \x01(\tR\x0esupportContact\x12=\n" +
	"\x06labels\x18\x05 \x03(\v2%.treasury.ServiceMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x01\n" +
	"\x13ServiceCapabilities\x12!\n" +
	"\fapi_versions\x18\x01 \x03(\tR\vapiVersions\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12?\n" +
	"\fdependencies\x18\x04 \x03(\v2\x1b.treasury.ServiceDependencyR\fdependencies\"b\n" +
	"\x11ServiceDependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vis_optional\x18\x03 \x01(\bR\n" +
	"isOptional\"\x11\n" +
	"\x0fLivenessRequest\"\xae\x01\n" +
	"\x10LivenessResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.treasury.ServiceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x06checks\x18\x03 \x03(\v2\x18.treasury.ComponentCheckR\x06checks\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x04 \x01(\tR\tcheckedAt\"e\n" +
	"\rHealthRequest\x12'\n" +
	"\x0finclude_details\x18\x01 \x01(\bR\x0eincludeDetails\x12+\n" +
	"\x11dependency_filter\x18\x02 \x03(\tR\x10dependencyFilter\"\x9a\x02\n" +
	"\x0eHealthResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.treasury.ServiceStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x122\n" +
	"\bliveness\x18\x03 \x01(\v2\x16.treasury.LivenessInfoR\bliveness\x12>\n" +
	"\fdependencies\x18\x04 \x03(\v2\x1a.treasury.DependencyHealthR\fdependencies\x12\x1d\n" +
	"\n" +
	"checked_at\x18\x05 \x01(\tR\tcheckedAt\x12*\n" +
	"\x11check_duration_ms\x18\x06 \x01(\x03R\x0fcheckDurationMs\"T\n" +
	"\x0eComponentCheck\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcc\x01\n" +
	"\fLivenessInfo\x12\x19\n" +
	"\bis_alive\x18\x01 \x01(\bR\aisAlive\x12#\n" +
	"\rconfig_loaded\x18\x02 \x01(\bR\fconfigLoaded\x12\x1f\n" +
	"\vpools_ready\x18\x03 \x01(\bR\n" +
	"poolsReady\x12!\n" +
	"\fcache_warmed\x18\x04 \x01(\bR\vcacheWarmed\x128\n" +
	"\n" +
	"components\x18\x05 \x03(\v2\x18.treasury.ComponentCheckR\n" +
	"components\"\xf6\x02\n" +
	"\x10DependencyHealth\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x02 \x01(\x0e2\x18.treasury.DependencyTypeR\x04type\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.treasury.ServiceStatusR\x06status\x12\x1f\n" +
	"\vis_critical\x18\x04 \x01(\bR\n" +
	"isCritical\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x122\n" +
	"\x06config\x18\x06 \x01(\v2\x1a.treasury.DependencyConfigR\x06config\x12!\n" +
	"\flast_success\x18\a \x01(\tR\vlastSuccess\x12\x1d\n" +
	"\n" +
	"last_check\x18\b \x01(\tR\tlastCheck\x12(\n" +
	"\x10response_time_ms\x18\t \x01(\x03R\x0eresponseTimeMs\x12\x14\n" +
	"\x05error\x18\n" +
	" \x01(\tR\x05error\"\x9b\x03\n" +
	"\x10DependencyConfig\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12#\n" +
	"\rdatabase_name\x18\x04 \x01(\tR\fdatabaseName\x12\x1f\n" +
	"\vschema_name\x18\x05 \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"topic_name\x18\x06 \x01(\tR\ttopicName\x129\n" +
	"\tpool_info\x18\a \x01(\v2\x1c.treasury.ConnectionPoolInfoR\bpoolInfo\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12D\n" +
	"\bmetadata\x18\t \x03(\v2(.treasury.DependencyConfig.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x01\n" +
	"\x12ConnectionPoolInfo\x12'\n" +
	"\x0fmax_connections\x18\x01 \x01(\x05R\x0emaxConnections\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x05R\x11activeConnections\x12)\n" +
	"\x10idle_connections\x18\x03 \x01(\x05R\x0fidleConnections\x12\x1d\n" +
	"\n" +
	"wait_count\x18\x04 \x01(\x05R\twaitCount\x12(\n" +
	"\x10wait_duration_ms\x18\x05 \x01(\x03R\x0ewaitDurationMs\"\xa8\x05\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12!\n" +
	"\fnumeric_code\x18\x03 \x01(\tR\vnumericCode\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1f\n" +
	"\vminor_units\x18\x05 \x01(\x05R\n" +
	"minorUnits\x12\x16\n" +
	"\x06symbol\x18\x06 \x01(\tR\x06symbol\x12'\n" +
	"\x0fsymbol_position\x18\a \x01(\tR\x0esymbolPosition\x12#\n" +
	"\rcountry_codes\x18\b \x03(\tR\fcountryCodes\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\x12\x1b\n" +
	"\tis_crypto\x18\n" +
	" \x01(\bR\bisCrypto\x120\n" +
	"\x06status\x18\v \x01(\x0e2\x18.treasury.CurrencyStatusR\x06status\x12=\n" +
	"\factivated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vactivatedAt\x12A\n" +
	"\x0edeactivated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rdeactivatedAt\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x10 \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x11 \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\x12 \x01(\x05R\aversion\"\xdd\x01\n" +
	"\x15CreateCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fnumeric_code\x18\x02 \x01(\tR\vnumericCode\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vminor_units\x18\x04 \x01(\x05R\n" +
	"minorUnits\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12#\n" +
	"\rcountry_codes\x18\x06 \x03(\tR\fcountryCodes\x12\x1b\n" +
	"\tis_crypto\x18\a \x01(\bR\bisCrypto\"H\n" +
	"\x16CreateCurrencyResponse\x12.\n" +
	"\bcurrency\x18\x01 \x01(\v2\x12.treasury.CurrencyR\bcurrency\"o\n" +
	"\x12GetCurrencyRequest\x12\x14\n" +
	"\x04code\x18\x01 \x01(\tH\x00R\x04code\x12#\n" +
	"\fnumeric_code\x18\x02 \x01(\tH\x00R\vnumericCode\x12\x10\n" +
	"\x02id\x18\x03 \x01(\tH\x00R\x02idB\f\n" +
	"\n" +
	"identifier\"E\n" +
	"\x13GetCurrencyResponse\x12.\n" +
	"\bcurrency\x18\x01 \x01(\v2\x12.treasury.CurrencyR\bcurrency\"\xa6\x02\n" +
	"\x15UpdateCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\vminor_units\x18\x04 \x01(\x05R\n" +
	"minorUnits\x12\x16\n" +
	"\x06symbol\x18\x05 \x01(\tR\x06symbol\x12#\n" +
	"\rcountry_codes\x18\x06 \x03(\tR\fcountryCodes\x120\n" +
	"\x06status\x18\a \x01(\x0e2\x18.treasury.CurrencyStatusR\x06status\x12\x18\n" +
	"\aversion\x18\b \x01(\x05R\aversion\"H\n" +
	"\x16UpdateCurrencyResponse\x12.\n" +
	"\bcurrency\x18\x01 \x01(\v2\x12.treasury.CurrencyR\bcurrency\"\x9a\x01\n" +
	"\x19DeactivateCurrencyRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.treasury.CurrencyStatusR\x06status\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x03 \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x05R\aversion\"f\n" +
	"\x1aDeactivateCurrencyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\bcurrency\x18\x02 \x01(\v2\x12.treasury.CurrencyR\bcurrency\"\xe2\x01\n" +
	"\x15ListCurrenciesRequest\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.treasury.CurrencyStatusR\x06status\x12\x1b\n" +
	"\tis_active\x18\x02 \x01(\bR\bisActive\x12\x1b\n" +
	"\tis_crypto\x18\x03 \x01(\bR\bisCrypto\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x06 \x01(\tR\tpageToken\"\x95\x01\n" +
	"\x16ListCurrenciesResponse\x122\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x12.treasury.CurrencyR\n" +
	"currencies\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xb0\x01\n" +
	"\x1bBulkCreateCurrenciesRequest\x12?\n" +
	"\n" +
	"currencies\x18\x01 \x03(\v2\x1f.treasury.CreateCurrencyRequestR\n" +
	"currencies\x12'\n" +
	"\x0fskip_duplicates\x18\x02 \x01(\bR\x0eskipDuplicates\x12'\n" +
	"\x0fupdate_existing\x18\x03 \x01(\bR\x0eupdateExisting\"\xa5\x01\n" +
	"\x1cBulkCreateCurrenciesResponse\x12#\n" +
	"\rcreated_count\x18\x01 \x01(\x05R\fcreatedCount\x12#\n" +
	"\rupdated_count\x18\x02 \x01(\x05R\fupdatedCount\x12#\n" +
	"\rskipped_count\x18\x03 \x01(\x05R\fskippedCount\x12\x16\n" +
	"\x06errors\x18\x04 \x03(\tR\x06errors*9\n" +
	"\rServiceStatus\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\f\n" +
	"\bDEGRADED\x10\x01\x12\r\n" +
	"\tUNHEALTHY\x10\x02*x\n" +
	"\x0eDependencyType\x12\f\n" +
	"\bDATABASE\x10\x00\x12\t\n" +
	"\x05CACHE\x10\x01\x12\x11\n" +
	"\rMESSAGE_QUEUE\x10\x02\x12\x10\n" +
	"\fGRPC_SERVICE\x10\x03\x12\x10\n" +
	"\fHTTP_SERVICE\x10\x04\x12\v\n" +
	"\aSTORAGE\x10\x05\x12\t\n" +
	"\x05OTHER\x10\x06*\xa8\x01\n" +
	"\x0eCurrencyStatus\x12\x1f\n" +
	"\x1bCURRENCY_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CURRENCY_STATUS_ACTIVE\x10\x01\x12\x1c\n" +
	"\x18CURRENCY_STATUS_INACTIVE\x10\x02\x12\x1e\n" +
	"\x1aCURRENCY_STATUS_DEPRECATED\x10\x03\x12\x1b\n" +
	"\x17CURRENCY_STATUS_DELETED\x10\x042R\n" +
	"\bManifest\x12F\n" +
	"\vGetManifest\x12\x19.treasury.ManifestRequest\x1a\x1a.treasury.ManifestResponse\"\x002\x92\x01\n" +
	"\x06Health\x12F\n" +
	"\vGetLiveness\x12\x19.treasury.LivenessRequest\x1a\x1a.treasury.LivenessResponse\"\x00\x12@\n" +
	"\tGetHealth\x12\x17.treasury.HealthRequest\x1a\x18.treasury.HealthResponse\"\x002\xa4\x04\n" +
	"\x0fCurrencyService\x12S\n" +
	"\x0eCreateCurrency\x12\x1f.treasury.CreateCurrencyRequest\x1a .treasury.CreateCurrencyResponse\x12J\n" +
	"\vGetCurrency\x12\x1c.treasury.GetCurrencyRequest\x1a\x1d.treasury.GetCurrencyResponse\x12S\n" +
	"\x0eUpdateCurrency\x12\x1f.treasury.UpdateCurrencyRequest\x1a .treasury.UpdateCurrencyResponse\x12_\n" +
	"\x12DeactivateCurrency\x12#.treasury.DeactivateCurrencyRequest\x1a$.treasury.DeactivateCurrencyResponse\x12S\n" +
	"\x0eListCurrencies\x12\x1f.treasury.ListCurrenciesRequest\x1a .treasury.ListCurrenciesResponse\x12e\n" +
	"\x14BulkCreateCurrencies\x12%.treasury.BulkCreateCurrenciesRequest\x1a&.treasury.BulkCreateCurrenciesResponseB)Z'example.com/go-mono-repo/proto/treasuryb\x06proto3"

var (
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescOnce sync.Once
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescData []byte
)

func file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescGZIP() []byte {
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescOnce.Do(func() {
		file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDesc), len(file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDesc)))
	})
	return file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDescData
}

var file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_services_treasury_services_treasury_service_proto_treasury_service_proto_goTypes = []any{
	(ServiceStatus)(0),                   // 0: treasury.ServiceStatus
	(DependencyType)(0),                  // 1: treasury.DependencyType
	(CurrencyStatus)(0),                  // 2: treasury.CurrencyStatus
	(*ManifestRequest)(nil),              // 3: treasury.ManifestRequest
	(*ManifestResponse)(nil),             // 4: treasury.ManifestResponse
	(*ServiceIdentity)(nil),              // 5: treasury.ServiceIdentity
	(*BuildInfo)(nil),                    // 6: treasury.BuildInfo
	(*RuntimeInfo)(nil),                  // 7: treasury.RuntimeInfo
	(*ServiceMetadata)(nil),              // 8: treasury.ServiceMetadata
	(*ServiceCapabilities)(nil),          // 9: treasury.ServiceCapabilities
	(*ServiceDependency)(nil),            // 10: treasury.ServiceDependency
	(*LivenessRequest)(nil),              // 11: treasury.LivenessRequest
	(*LivenessResponse)(nil),             // 12: treasury.LivenessResponse
	(*HealthRequest)(nil),                // 13: treasury.HealthRequest
	(*HealthResponse)(nil),               // 14: treasury.HealthResponse
	(*ComponentCheck)(nil),               // 15: treasury.ComponentCheck
	(*LivenessInfo)(nil),                 // 16: treasury.LivenessInfo
	(*DependencyHealth)(nil),             // 17: treasury.DependencyHealth
	(*DependencyConfig)(nil),             // 18: treasury.DependencyConfig
	(*ConnectionPoolInfo)(nil),           // 19: treasury.ConnectionPoolInfo
	(*Currency)(nil),                     // 20: treasury.Currency
	(*CreateCurrencyRequest)(nil),        // 21: treasury.CreateCurrencyRequest
	(*CreateCurrencyResponse)(nil),       // 22: treasury.CreateCurrencyResponse
	(*GetCurrencyRequest)(nil),           // 23: treasury.GetCurrencyRequest
	(*GetCurrencyResponse)(nil),          // 24: treasury.GetCurrencyResponse
	(*UpdateCurrencyRequest)(nil),        // 25: treasury.UpdateCurrencyRequest
	(*UpdateCurrencyResponse)(nil),       // 26: treasury.UpdateCurrencyResponse
	(*DeactivateCurrencyRequest)(nil),    // 27: treasury.DeactivateCurrencyRequest
	(*DeactivateCurrencyResponse)(nil),   // 28: treasury.DeactivateCurrencyResponse
	(*ListCurrenciesRequest)(nil),        // 29: treasury.ListCurrenciesRequest
	(*ListCurrenciesResponse)(nil),       // 30: treasury.ListCurrenciesResponse
	(*BulkCreateCurrenciesRequest)(nil),  // 31: treasury.BulkCreateCurrenciesRequest
	(*BulkCreateCurrenciesResponse)(nil), // 32: treasury.BulkCreateCurrenciesResponse
	nil,                                  // 33: treasury.ServiceMetadata.LabelsEntry
	nil,                                  // 34: treasury.DependencyConfig.MetadataEntry
	(*timestamppb.Timestamp)(nil),        // 35: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),        // 36: google.protobuf.FieldMask
}
var file_services_treasury_services_treasury_service_proto_treasury_service_proto_depIdxs = []int32{
	5,  // 0: treasury.ManifestResponse.identity:type_name -> treasury.ServiceIdentity
	6,  // 1: treasury.ManifestResponse.build_info:type_name -> treasury.BuildInfo
	7,  // 2: treasury.ManifestResponse.runtime_info:type_name -> treasury.RuntimeInfo
	8,  // 3: treasury.ManifestResponse.metadata:type_name -> treasury.ServiceMetadata
	9,  // 4: treasury.ManifestResponse.capabilities:type_name -> treasury.ServiceCapabilities
	33, // 5: treasury.ServiceMetadata.labels:type_name -> treasury.ServiceMetadata.LabelsEntry
	10, // 6: treasury.ServiceCapabilities.dependencies:type_name -> treasury.ServiceDependency
	0,  // 7: treasury.LivenessResponse.status:type_name -> treasury.ServiceStatus
	15, // 8: treasury.LivenessResponse.checks:type_name -> treasury.ComponentCheck
	0,  // 9: treasury.HealthResponse.status:type_name -> treasury.ServiceStatus
	16, // 10: treasury.HealthResponse.liveness:type_name -> treasury.LivenessInfo
	17, // 11: treasury.HealthResponse.dependencies:type_name -> treasury.DependencyHealth
	15, // 12: treasury.LivenessInfo.components:type_name -> treasury.ComponentCheck
	1,  // 13: treasury.DependencyHealth.type:type_name -> treasury.DependencyType
	0,  // 14: treasury.DependencyHealth.status:type_name -> treasury.ServiceStatus
	18, // 15: treasury.DependencyHealth.config:type_name -> treasury.DependencyConfig
	19, // 16: treasury.DependencyConfig.pool_info:type_name -> treasury.ConnectionPoolInfo
	34, // 17: treasury.DependencyConfig.metadata:type_name -> treasury.DependencyConfig.MetadataEntry
	2,  // 18: treasury.Currency.status:type_name -> treasury.CurrencyStatus
	35, // 19: treasury.Currency.activated_at:type_name -> google.protobuf.Timestamp
	35, // 20: treasury.Currency.deactivated_at:type_name -> google.protobuf.Timestamp
	35, // 21: treasury.Currency.created_at:type_name -> google.protobuf.Timestamp
	35, // 22: treasury.Currency.updated_at:type_name -> google.protobuf.Timestamp
	20, // 23: treasury.CreateCurrencyResponse.currency:type_name -> treasury.Currency
	20, // 24: treasury.GetCurrencyResponse.currency:type_name -> treasury.Currency
	36, // 25: treasury.UpdateCurrencyRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 26: treasury.UpdateCurrencyRequest.status:type_name -> treasury.CurrencyStatus
	20, // 27: treasury.UpdateCurrencyResponse.currency:type_name -> treasury.Currency
	2,  // 28: treasury.DeactivateCurrencyRequest.status:type_name -> treasury.CurrencyStatus
	20, // 29: treasury.DeactivateCurrencyResponse.currency:type_name -> treasury.Currency
	2,  // 30: treasury.ListCurrenciesRequest.status:type_name -> treasury.CurrencyStatus
	20, // 31: treasury.ListCurrenciesResponse.currencies:type_name -> treasury.Currency
	21, // 32: treasury.BulkCreateCurrenciesRequest.currencies:type_name -> treasury.CreateCurrencyRequest
	3,  // 33: treasury.Manifest.GetManifest:input_type -> treasury.ManifestRequest
	11, // 34: treasury.Health.GetLiveness:input_type -> treasury.LivenessRequest
	13, // 35: treasury.Health.GetHealth:input_type -> treasury.HealthRequest
	21, // 36: treasury.CurrencyService.CreateCurrency:input_type -> treasury.CreateCurrencyRequest
	23, // 37: treasury.CurrencyService.GetCurrency:input_type -> treasury.GetCurrencyRequest
	25, // 38: treasury.CurrencyService.UpdateCurrency:input_type -> treasury.UpdateCurrencyRequest
	27, // 39: treasury.CurrencyService.DeactivateCurrency:input_type -> treasury.DeactivateCurrencyRequest
	29, // 40: treasury.CurrencyService.ListCurrencies:input_type -> treasury.ListCurrenciesRequest
	31, // 41: treasury.CurrencyService.BulkCreateCurrencies:input_type -> treasury.BulkCreateCurrenciesRequest
	4,  // 42: treasury.Manifest.GetManifest:output_type -> treasury.ManifestResponse
	12, // 43: treasury.Health.GetLiveness:output_type -> treasury.LivenessResponse
	14, // 44: treasury.Health.GetHealth:output_type -> treasury.HealthResponse
	22, // 45: treasury.CurrencyService.CreateCurrency:output_type -> treasury.CreateCurrencyResponse
	24, // 46: treasury.CurrencyService.GetCurrency:output_type -> treasury.GetCurrencyResponse
	26, // 47: treasury.CurrencyService.UpdateCurrency:output_type -> treasury.UpdateCurrencyResponse
	28, // 48: treasury.CurrencyService.DeactivateCurrency:output_type -> treasury.DeactivateCurrencyResponse
	30, // 49: treasury.CurrencyService.ListCurrencies:output_type -> treasury.ListCurrenciesResponse
	32, // 50: treasury.CurrencyService.BulkCreateCurrencies:output_type -> treasury.BulkCreateCurrenciesResponse
	42, // [42:51] is the sub-list for method output_type
	33, // [33:42] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_services_treasury_services_treasury_service_proto_treasury_service_proto_init() }
func file_services_treasury_services_treasury_service_proto_treasury_service_proto_init() {
	if File_services_treasury_services_treasury_service_proto_treasury_service_proto != nil {
		return
	}
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes[20].OneofWrappers = []any{
		(*GetCurrencyRequest_Code)(nil),
		(*GetCurrencyRequest_NumericCode)(nil),
		(*GetCurrencyRequest_Id)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDesc), len(file_services_treasury_services_treasury_service_proto_treasury_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_treasury_services_treasury_service_proto_treasury_service_proto_goTypes,
		DependencyIndexes: file_services_treasury_services_treasury_service_proto_treasury_service_proto_depIdxs,
		EnumInfos:         file_services_treasury_services_treasury_service_proto_treasury_service_proto_enumTypes,
		MessageInfos:      file_services_treasury_services_treasury_service_proto_treasury_service_proto_msgTypes,
	}.Build()
	File_services_treasury_services_treasury_service_proto_treasury_service_proto = out.File
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_goTypes = nil
	file_services_treasury_services_treasury_service_proto_treasury_service_proto_depIdxs = nil
}
