// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0--rc2
// source: services/treasury-services/treasury-service/proto/treasury_service.proto

package treasury

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Manifest_GetManifest_FullMethodName = "/treasury.Manifest/GetManifest"
)

// ManifestClient is the client API for Manifest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Spec: docs/specs/001-manifest.md
type ManifestClient interface {
	// GetManifest returns comprehensive service metadata
	GetManifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error)
}

type manifestClient struct {
	cc grpc.ClientConnInterface
}

func NewManifestClient(cc grpc.ClientConnInterface) ManifestClient {
	return &manifestClient{cc}
}

func (c *manifestClient) GetManifest(ctx context.Context, in *ManifestRequest, opts ...grpc.CallOption) (*ManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManifestResponse)
	err := c.cc.Invoke(ctx, Manifest_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManifestServer is the server API for Manifest service.
// All implementations must embed UnimplementedManifestServer
// for forward compatibility.
//
// Spec: docs/specs/001-manifest.md
type ManifestServer interface {
	// GetManifest returns comprehensive service metadata
	GetManifest(context.Context, *ManifestRequest) (*ManifestResponse, error)
	mustEmbedUnimplementedManifestServer()
}

// UnimplementedManifestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManifestServer struct{}

func (UnimplementedManifestServer) GetManifest(context.Context, *ManifestRequest) (*ManifestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedManifestServer) mustEmbedUnimplementedManifestServer() {}
func (UnimplementedManifestServer) testEmbeddedByValue()                  {}

// UnsafeManifestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManifestServer will
// result in compilation errors.
type UnsafeManifestServer interface {
	mustEmbedUnimplementedManifestServer()
}

func RegisterManifestServer(s grpc.ServiceRegistrar, srv ManifestServer) {
	// If the following call pancis, it indicates UnimplementedManifestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Manifest_ServiceDesc, srv)
}

func _Manifest_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManifestServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Manifest_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManifestServer).GetManifest(ctx, req.(*ManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Manifest_ServiceDesc is the grpc.ServiceDesc for Manifest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Manifest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treasury.Manifest",
	HandlerType: (*ManifestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _Manifest_GetManifest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/treasury-services/treasury-service/proto/treasury_service.proto",
}

const (
	Health_GetLiveness_FullMethodName = "/treasury.Health/GetLiveness"
	Health_GetHealth_FullMethodName   = "/treasury.Health/GetHealth"
)

// HealthClient is the client API for Health service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthClient interface {
	// GetLiveness checks if the service is alive and ready to accept traffic
	// Should be used by load balancers and orchestrators
	// Spec: docs/specs/003-health-check-liveness.md#story-1-service-liveness-check
	GetLiveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error)
	// GetHealth performs comprehensive health check including dependencies
	// Should be used for monitoring and debugging
	// Spec: docs/specs/003-health-check-liveness.md#story-2-dependency-health-monitoring
	GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type healthClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthClient(cc grpc.ClientConnInterface) HealthClient {
	return &healthClient{cc}
}

func (c *healthClient) GetLiveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LivenessResponse)
	err := c.cc.Invoke(ctx, Health_GetLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *healthClient) GetHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, Health_GetHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HealthServer is the server API for Health service.
// All implementations must embed UnimplementedHealthServer
// for forward compatibility.
type HealthServer interface {
	// GetLiveness checks if the service is alive and ready to accept traffic
	// Should be used by load balancers and orchestrators
	// Spec: docs/specs/003-health-check-liveness.md#story-1-service-liveness-check
	GetLiveness(context.Context, *LivenessRequest) (*LivenessResponse, error)
	// GetHealth performs comprehensive health check including dependencies
	// Should be used for monitoring and debugging
	// Spec: docs/specs/003-health-check-liveness.md#story-2-dependency-health-monitoring
	GetHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHealthServer()
}

// UnimplementedHealthServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHealthServer struct{}

func (UnimplementedHealthServer) GetLiveness(context.Context, *LivenessRequest) (*LivenessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLiveness not implemented")
}
func (UnimplementedHealthServer) GetHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHealth not implemented")
}
func (UnimplementedHealthServer) mustEmbedUnimplementedHealthServer() {}
func (UnimplementedHealthServer) testEmbeddedByValue()                {}

// UnsafeHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthServer will
// result in compilation errors.
type UnsafeHealthServer interface {
	mustEmbedUnimplementedHealthServer()
}

func RegisterHealthServer(s grpc.ServiceRegistrar, srv HealthServer) {
	// If the following call pancis, it indicates UnimplementedHealthServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Health_ServiceDesc, srv)
}

func _Health_GetLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).GetLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_GetLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).GetLiveness(ctx, req.(*LivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Health_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HealthServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Health_GetHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HealthServer).GetHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Health_ServiceDesc is the grpc.ServiceDesc for Health service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Health_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treasury.Health",
	HandlerType: (*HealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLiveness",
			Handler:    _Health_GetLiveness_Handler,
		},
		{
			MethodName: "GetHealth",
			Handler:    _Health_GetHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/treasury-services/treasury-service/proto/treasury_service.proto",
}

const (
	CurrencyService_CreateCurrency_FullMethodName       = "/treasury.CurrencyService/CreateCurrency"
	CurrencyService_GetCurrency_FullMethodName          = "/treasury.CurrencyService/GetCurrency"
	CurrencyService_UpdateCurrency_FullMethodName       = "/treasury.CurrencyService/UpdateCurrency"
	CurrencyService_DeactivateCurrency_FullMethodName   = "/treasury.CurrencyService/DeactivateCurrency"
	CurrencyService_ListCurrencies_FullMethodName       = "/treasury.CurrencyService/ListCurrencies"
	CurrencyService_BulkCreateCurrencies_FullMethodName = "/treasury.CurrencyService/BulkCreateCurrencies"
)

// CurrencyServiceClient is the client API for CurrencyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Currency service for managing ISO 4217 compliant currencies
type CurrencyServiceClient interface {
	// Create a new currency
	// Spec: docs/specs/003-currency-management.md#story-1-create-new-currency
	CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error)
	// Get currency information
	// Spec: docs/specs/003-currency-management.md#story-2-query-currency-information
	GetCurrency(ctx context.Context, in *GetCurrencyRequest, opts ...grpc.CallOption) (*GetCurrencyResponse, error)
	// Update currency metadata
	// Spec: docs/specs/003-currency-management.md#story-3-update-currency-metadata
	UpdateCurrency(ctx context.Context, in *UpdateCurrencyRequest, opts ...grpc.CallOption) (*UpdateCurrencyResponse, error)
	// Deactivate currency (soft delete only - hard delete not supported)
	// Spec: docs/specs/003-currency-management.md#story-4-deactivate-currency
	DeactivateCurrency(ctx context.Context, in *DeactivateCurrencyRequest, opts ...grpc.CallOption) (*DeactivateCurrencyResponse, error)
	// List currencies with filters
	// Spec: docs/specs/003-currency-management.md#story-2-query-currency-information
	ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error)
	// Bulk create currencies
	// Spec: docs/specs/003-currency-management.md#story-5-bulk-currency-operations
	BulkCreateCurrencies(ctx context.Context, in *BulkCreateCurrenciesRequest, opts ...grpc.CallOption) (*BulkCreateCurrenciesResponse, error)
}

type currencyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCurrencyServiceClient(cc grpc.ClientConnInterface) CurrencyServiceClient {
	return &currencyServiceClient{cc}
}

func (c *currencyServiceClient) CreateCurrency(ctx context.Context, in *CreateCurrencyRequest, opts ...grpc.CallOption) (*CreateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_CreateCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) GetCurrency(ctx context.Context, in *GetCurrencyRequest, opts ...grpc.CallOption) (*GetCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_GetCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) UpdateCurrency(ctx context.Context, in *UpdateCurrencyRequest, opts ...grpc.CallOption) (*UpdateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_UpdateCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) DeactivateCurrency(ctx context.Context, in *DeactivateCurrencyRequest, opts ...grpc.CallOption) (*DeactivateCurrencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateCurrencyResponse)
	err := c.cc.Invoke(ctx, CurrencyService_DeactivateCurrency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) ListCurrencies(ctx context.Context, in *ListCurrenciesRequest, opts ...grpc.CallOption) (*ListCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_ListCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currencyServiceClient) BulkCreateCurrencies(ctx context.Context, in *BulkCreateCurrenciesRequest, opts ...grpc.CallOption) (*BulkCreateCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkCreateCurrenciesResponse)
	err := c.cc.Invoke(ctx, CurrencyService_BulkCreateCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CurrencyServiceServer is the server API for CurrencyService service.
// All implementations must embed UnimplementedCurrencyServiceServer
// for forward compatibility.
//
// Currency service for managing ISO 4217 compliant currencies
type CurrencyServiceServer interface {
	// Create a new currency
	// Spec: docs/specs/003-currency-management.md#story-1-create-new-currency
	CreateCurrency(context.Context, *CreateCurrencyRequest) (*CreateCurrencyResponse, error)
	// Get currency information
	// Spec: docs/specs/003-currency-management.md#story-2-query-currency-information
	GetCurrency(context.Context, *GetCurrencyRequest) (*GetCurrencyResponse, error)
	// Update currency metadata
	// Spec: docs/specs/003-currency-management.md#story-3-update-currency-metadata
	UpdateCurrency(context.Context, *UpdateCurrencyRequest) (*UpdateCurrencyResponse, error)
	// Deactivate currency (soft delete only - hard delete not supported)
	// Spec: docs/specs/003-currency-management.md#story-4-deactivate-currency
	DeactivateCurrency(context.Context, *DeactivateCurrencyRequest) (*DeactivateCurrencyResponse, error)
	// List currencies with filters
	// Spec: docs/specs/003-currency-management.md#story-2-query-currency-information
	ListCurrencies(context.Context, *ListCurrenciesRequest) (*ListCurrenciesResponse, error)
	// Bulk create currencies
	// Spec: docs/specs/003-currency-management.md#story-5-bulk-currency-operations
	BulkCreateCurrencies(context.Context, *BulkCreateCurrenciesRequest) (*BulkCreateCurrenciesResponse, error)
	mustEmbedUnimplementedCurrencyServiceServer()
}

// UnimplementedCurrencyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCurrencyServiceServer struct{}

func (UnimplementedCurrencyServiceServer) CreateCurrency(context.Context, *CreateCurrencyRequest) (*CreateCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCurrency not implemented")
}
func (UnimplementedCurrencyServiceServer) GetCurrency(context.Context, *GetCurrencyRequest) (*GetCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrency not implemented")
}
func (UnimplementedCurrencyServiceServer) UpdateCurrency(context.Context, *UpdateCurrencyRequest) (*UpdateCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCurrency not implemented")
}
func (UnimplementedCurrencyServiceServer) DeactivateCurrency(context.Context, *DeactivateCurrencyRequest) (*DeactivateCurrencyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateCurrency not implemented")
}
func (UnimplementedCurrencyServiceServer) ListCurrencies(context.Context, *ListCurrenciesRequest) (*ListCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCurrencies not implemented")
}
func (UnimplementedCurrencyServiceServer) BulkCreateCurrencies(context.Context, *BulkCreateCurrenciesRequest) (*BulkCreateCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkCreateCurrencies not implemented")
}
func (UnimplementedCurrencyServiceServer) mustEmbedUnimplementedCurrencyServiceServer() {}
func (UnimplementedCurrencyServiceServer) testEmbeddedByValue()                         {}

// UnsafeCurrencyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CurrencyServiceServer will
// result in compilation errors.
type UnsafeCurrencyServiceServer interface {
	mustEmbedUnimplementedCurrencyServiceServer()
}

func RegisterCurrencyServiceServer(s grpc.ServiceRegistrar, srv CurrencyServiceServer) {
	// If the following call pancis, it indicates UnimplementedCurrencyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CurrencyService_ServiceDesc, srv)
}

func _CurrencyService_CreateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).CreateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_CreateCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).CreateCurrency(ctx, req.(*CreateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_GetCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).GetCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_GetCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).GetCurrency(ctx, req.(*GetCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_UpdateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).UpdateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_UpdateCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).UpdateCurrency(ctx, req.(*UpdateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_DeactivateCurrency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateCurrencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).DeactivateCurrency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_DeactivateCurrency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).DeactivateCurrency(ctx, req.(*DeactivateCurrencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_ListCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).ListCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_ListCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).ListCurrencies(ctx, req.(*ListCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrencyService_BulkCreateCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCreateCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrencyServiceServer).BulkCreateCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CurrencyService_BulkCreateCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrencyServiceServer).BulkCreateCurrencies(ctx, req.(*BulkCreateCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CurrencyService_ServiceDesc is the grpc.ServiceDesc for CurrencyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CurrencyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treasury.CurrencyService",
	HandlerType: (*CurrencyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCurrency",
			Handler:    _CurrencyService_CreateCurrency_Handler,
		},
		{
			MethodName: "GetCurrency",
			Handler:    _CurrencyService_GetCurrency_Handler,
		},
		{
			MethodName: "UpdateCurrency",
			Handler:    _CurrencyService_UpdateCurrency_Handler,
		},
		{
			MethodName: "DeactivateCurrency",
			Handler:    _CurrencyService_DeactivateCurrency_Handler,
		},
		{
			MethodName: "ListCurrencies",
			Handler:    _CurrencyService_ListCurrencies_Handler,
		},
		{
			MethodName: "BulkCreateCurrencies",
			Handler:    _CurrencyService_BulkCreateCurrencies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/treasury-services/treasury-service/proto/treasury_service.proto",
}

const (
	FinancialInstitutionService_CreateInstitution_FullMethodName          = "/treasury.FinancialInstitutionService/CreateInstitution"
	FinancialInstitutionService_GetInstitution_FullMethodName             = "/treasury.FinancialInstitutionService/GetInstitution"
	FinancialInstitutionService_UpdateInstitution_FullMethodName          = "/treasury.FinancialInstitutionService/UpdateInstitution"
	FinancialInstitutionService_DeleteInstitution_FullMethodName          = "/treasury.FinancialInstitutionService/DeleteInstitution"
	FinancialInstitutionService_ListInstitutions_FullMethodName           = "/treasury.FinancialInstitutionService/ListInstitutions"
	FinancialInstitutionService_CheckInstitutionReferences_FullMethodName = "/treasury.FinancialInstitutionService/CheckInstitutionReferences"
	FinancialInstitutionService_BulkCreateInstitutions_FullMethodName     = "/treasury.FinancialInstitutionService/BulkCreateInstitutions"
)

// FinancialInstitutionServiceClient is the client API for FinancialInstitutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Financial institutions management service
type FinancialInstitutionServiceClient interface {
	// Create a new financial institution
	// Spec: docs/specs/004-financial-institutions.md#story-1-create-new-financial-institution
	CreateInstitution(ctx context.Context, in *CreateInstitutionRequest, opts ...grpc.CallOption) (*CreateInstitutionResponse, error)
	// Get institution information
	// Spec: docs/specs/004-financial-institutions.md#story-2-query-financial-institution-information
	GetInstitution(ctx context.Context, in *GetInstitutionRequest, opts ...grpc.CallOption) (*GetInstitutionResponse, error)
	// Update institution metadata
	// Spec: docs/specs/004-financial-institutions.md#story-3-update-institution-information
	UpdateInstitution(ctx context.Context, in *UpdateInstitutionRequest, opts ...grpc.CallOption) (*UpdateInstitutionResponse, error)
	// Delete institution (with reference checking)
	// Spec: docs/specs/004-financial-institutions.md#story-4-deactivate-financial-institution
	DeleteInstitution(ctx context.Context, in *DeleteInstitutionRequest, opts ...grpc.CallOption) (*DeleteInstitutionResponse, error)
	// List institutions with filters
	// Spec: docs/specs/004-financial-institutions.md#story-2-query-financial-institution-information
	ListInstitutions(ctx context.Context, in *ListInstitutionsRequest, opts ...grpc.CallOption) (*ListInstitutionsResponse, error)
	// Check for references before deletion
	// Spec: docs/specs/004-financial-institutions.md#story-4-deactivate-financial-institution
	CheckInstitutionReferences(ctx context.Context, in *CheckInstitutionReferencesRequest, opts ...grpc.CallOption) (*CheckInstitutionReferencesResponse, error)
	// Bulk create institutions
	// Spec: docs/specs/004-financial-institutions.md#story-5-bulk-institution-operations
	BulkCreateInstitutions(ctx context.Context, in *BulkCreateInstitutionsRequest, opts ...grpc.CallOption) (*BulkCreateInstitutionsResponse, error)
}

type financialInstitutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFinancialInstitutionServiceClient(cc grpc.ClientConnInterface) FinancialInstitutionServiceClient {
	return &financialInstitutionServiceClient{cc}
}

func (c *financialInstitutionServiceClient) CreateInstitution(ctx context.Context, in *CreateInstitutionRequest, opts ...grpc.CallOption) (*CreateInstitutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstitutionResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_CreateInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) GetInstitution(ctx context.Context, in *GetInstitutionRequest, opts ...grpc.CallOption) (*GetInstitutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstitutionResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_GetInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) UpdateInstitution(ctx context.Context, in *UpdateInstitutionRequest, opts ...grpc.CallOption) (*UpdateInstitutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateInstitutionResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_UpdateInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) DeleteInstitution(ctx context.Context, in *DeleteInstitutionRequest, opts ...grpc.CallOption) (*DeleteInstitutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInstitutionResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_DeleteInstitution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) ListInstitutions(ctx context.Context, in *ListInstitutionsRequest, opts ...grpc.CallOption) (*ListInstitutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstitutionsResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_ListInstitutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) CheckInstitutionReferences(ctx context.Context, in *CheckInstitutionReferencesRequest, opts ...grpc.CallOption) (*CheckInstitutionReferencesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckInstitutionReferencesResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_CheckInstitutionReferences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *financialInstitutionServiceClient) BulkCreateInstitutions(ctx context.Context, in *BulkCreateInstitutionsRequest, opts ...grpc.CallOption) (*BulkCreateInstitutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BulkCreateInstitutionsResponse)
	err := c.cc.Invoke(ctx, FinancialInstitutionService_BulkCreateInstitutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinancialInstitutionServiceServer is the server API for FinancialInstitutionService service.
// All implementations must embed UnimplementedFinancialInstitutionServiceServer
// for forward compatibility.
//
// Financial institutions management service
type FinancialInstitutionServiceServer interface {
	// Create a new financial institution
	// Spec: docs/specs/004-financial-institutions.md#story-1-create-new-financial-institution
	CreateInstitution(context.Context, *CreateInstitutionRequest) (*CreateInstitutionResponse, error)
	// Get institution information
	// Spec: docs/specs/004-financial-institutions.md#story-2-query-financial-institution-information
	GetInstitution(context.Context, *GetInstitutionRequest) (*GetInstitutionResponse, error)
	// Update institution metadata
	// Spec: docs/specs/004-financial-institutions.md#story-3-update-institution-information
	UpdateInstitution(context.Context, *UpdateInstitutionRequest) (*UpdateInstitutionResponse, error)
	// Delete institution (with reference checking)
	// Spec: docs/specs/004-financial-institutions.md#story-4-deactivate-financial-institution
	DeleteInstitution(context.Context, *DeleteInstitutionRequest) (*DeleteInstitutionResponse, error)
	// List institutions with filters
	// Spec: docs/specs/004-financial-institutions.md#story-2-query-financial-institution-information
	ListInstitutions(context.Context, *ListInstitutionsRequest) (*ListInstitutionsResponse, error)
	// Check for references before deletion
	// Spec: docs/specs/004-financial-institutions.md#story-4-deactivate-financial-institution
	CheckInstitutionReferences(context.Context, *CheckInstitutionReferencesRequest) (*CheckInstitutionReferencesResponse, error)
	// Bulk create institutions
	// Spec: docs/specs/004-financial-institutions.md#story-5-bulk-institution-operations
	BulkCreateInstitutions(context.Context, *BulkCreateInstitutionsRequest) (*BulkCreateInstitutionsResponse, error)
	mustEmbedUnimplementedFinancialInstitutionServiceServer()
}

// UnimplementedFinancialInstitutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFinancialInstitutionServiceServer struct{}

func (UnimplementedFinancialInstitutionServiceServer) CreateInstitution(context.Context, *CreateInstitutionRequest) (*CreateInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstitution not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) GetInstitution(context.Context, *GetInstitutionRequest) (*GetInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstitution not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) UpdateInstitution(context.Context, *UpdateInstitutionRequest) (*UpdateInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateInstitution not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) DeleteInstitution(context.Context, *DeleteInstitutionRequest) (*DeleteInstitutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstitution not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) ListInstitutions(context.Context, *ListInstitutionsRequest) (*ListInstitutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstitutions not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) CheckInstitutionReferences(context.Context, *CheckInstitutionReferencesRequest) (*CheckInstitutionReferencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckInstitutionReferences not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) BulkCreateInstitutions(context.Context, *BulkCreateInstitutionsRequest) (*BulkCreateInstitutionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkCreateInstitutions not implemented")
}
func (UnimplementedFinancialInstitutionServiceServer) mustEmbedUnimplementedFinancialInstitutionServiceServer() {
}
func (UnimplementedFinancialInstitutionServiceServer) testEmbeddedByValue() {}

// UnsafeFinancialInstitutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinancialInstitutionServiceServer will
// result in compilation errors.
type UnsafeFinancialInstitutionServiceServer interface {
	mustEmbedUnimplementedFinancialInstitutionServiceServer()
}

func RegisterFinancialInstitutionServiceServer(s grpc.ServiceRegistrar, srv FinancialInstitutionServiceServer) {
	// If the following call pancis, it indicates UnimplementedFinancialInstitutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FinancialInstitutionService_ServiceDesc, srv)
}

func _FinancialInstitutionService_CreateInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).CreateInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_CreateInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).CreateInstitution(ctx, req.(*CreateInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_GetInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).GetInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_GetInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).GetInstitution(ctx, req.(*GetInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_UpdateInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).UpdateInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_UpdateInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).UpdateInstitution(ctx, req.(*UpdateInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_DeleteInstitution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstitutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).DeleteInstitution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_DeleteInstitution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).DeleteInstitution(ctx, req.(*DeleteInstitutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_ListInstitutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstitutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).ListInstitutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_ListInstitutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).ListInstitutions(ctx, req.(*ListInstitutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_CheckInstitutionReferences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckInstitutionReferencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).CheckInstitutionReferences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_CheckInstitutionReferences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).CheckInstitutionReferences(ctx, req.(*CheckInstitutionReferencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinancialInstitutionService_BulkCreateInstitutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCreateInstitutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinancialInstitutionServiceServer).BulkCreateInstitutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FinancialInstitutionService_BulkCreateInstitutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinancialInstitutionServiceServer).BulkCreateInstitutions(ctx, req.(*BulkCreateInstitutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FinancialInstitutionService_ServiceDesc is the grpc.ServiceDesc for FinancialInstitutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinancialInstitutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "treasury.FinancialInstitutionService",
	HandlerType: (*FinancialInstitutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateInstitution",
			Handler:    _FinancialInstitutionService_CreateInstitution_Handler,
		},
		{
			MethodName: "GetInstitution",
			Handler:    _FinancialInstitutionService_GetInstitution_Handler,
		},
		{
			MethodName: "UpdateInstitution",
			Handler:    _FinancialInstitutionService_UpdateInstitution_Handler,
		},
		{
			MethodName: "DeleteInstitution",
			Handler:    _FinancialInstitutionService_DeleteInstitution_Handler,
		},
		{
			MethodName: "ListInstitutions",
			Handler:    _FinancialInstitutionService_ListInstitutions_Handler,
		},
		{
			MethodName: "CheckInstitutionReferences",
			Handler:    _FinancialInstitutionService_CheckInstitutionReferences_Handler,
		},
		{
			MethodName: "BulkCreateInstitutions",
			Handler:    _FinancialInstitutionService_BulkCreateInstitutions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/treasury-services/treasury-service/proto/treasury_service.proto",
}
