// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: services/payroll-services/payroll-service/proto/payroll_service.proto

package payroll

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{0}
}

type ManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Service identity
	Identity *ServiceIdentity `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	// Build information
	BuildInfo *BuildInfo `protobuf:"bytes,2,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	// Runtime information
	RuntimeInfo *RuntimeInfo `protobuf:"bytes,3,opt,name=runtime_info,json=runtimeInfo,proto3" json:"runtime_info,omitempty"`
	// Service metadata
	Metadata *ServiceMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Service capabilities
	Capabilities  *ServiceCapabilities `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetIdentity() *ServiceIdentity {
	if x != nil {
		return x.Identity
	}
	return nil
}

func (x *ManifestResponse) GetBuildInfo() *BuildInfo {
	if x != nil {
		return x.BuildInfo
	}
	return nil
}

func (x *ManifestResponse) GetRuntimeInfo() *RuntimeInfo {
	if x != nil {
		return x.RuntimeInfo
	}
	return nil
}

func (x *ManifestResponse) GetMetadata() *ServiceMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ManifestResponse) GetCapabilities() *ServiceCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServiceIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                               // Service name (e.g., "payroll-service")
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                         // Semantic version (e.g., "1.0.0")
	ApiVersion    string                 `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // API version (e.g., "v1")
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`                 // Brief service description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceIdentity) Reset() {
	*x = ServiceIdentity{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceIdentity) ProtoMessage() {}

func (x *ServiceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceIdentity.ProtoReflect.Descriptor instead.
func (*ServiceIdentity) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceIdentity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceIdentity) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceIdentity) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ServiceIdentity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type BuildInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitHash    string                 `protobuf:"bytes,1,opt,name=commit_hash,json=commitHash,proto3" json:"commit_hash,omitempty"` // Git commit SHA
	Branch        string                 `protobuf:"bytes,2,opt,name=branch,proto3" json:"branch,omitempty"`                           // Git branch name
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`    // RFC3339 timestamp
	Builder       string                 `protobuf:"bytes,4,opt,name=builder,proto3" json:"builder,omitempty"`                         // CI system or user
	IsDirty       bool                   `protobuf:"varint,5,opt,name=is_dirty,json=isDirty,proto3" json:"is_dirty,omitempty"`         // Whether build had uncommitted changes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildInfo) Reset() {
	*x = BuildInfo{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildInfo) ProtoMessage() {}

func (x *BuildInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildInfo.ProtoReflect.Descriptor instead.
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{3}
}

func (x *BuildInfo) GetCommitHash() string {
	if x != nil {
		return x.CommitHash
	}
	return ""
}

func (x *BuildInfo) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *BuildInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *BuildInfo) GetBuilder() string {
	if x != nil {
		return x.Builder
	}
	return ""
}

func (x *BuildInfo) GetIsDirty() bool {
	if x != nil {
		return x.IsDirty
	}
	return false
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`           // Unique instance identifier
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`                                 // Host machine name
	StartedAt     string                 `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`              // RFC3339 timestamp
	Environment   string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`                           // Environment (dev/staging/prod)
	Region        string                 `protobuf:"bytes,5,opt,name=region,proto3" json:"region,omitempty"`                                     // Deployment region/zone
	UptimeSeconds int64                  `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"` // Seconds since start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{4}
}

func (x *RuntimeInfo) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *RuntimeInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RuntimeInfo) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RuntimeInfo) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *RuntimeInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RuntimeInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type ServiceMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Owner            string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`                                                                             // Team or owner email
	RepositoryUrl    string                 `protobuf:"bytes,2,opt,name=repository_url,json=repositoryUrl,proto3" json:"repository_url,omitempty"`                                        // Source code repository
	DocumentationUrl string                 `protobuf:"bytes,3,opt,name=documentation_url,json=documentationUrl,proto3" json:"documentation_url,omitempty"`                               // Service documentation
	SupportContact   string                 `protobuf:"bytes,4,opt,name=support_contact,json=supportContact,proto3" json:"support_contact,omitempty"`                                     // Support contact info
	Labels           map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional labels/tags
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ServiceMetadata) Reset() {
	*x = ServiceMetadata{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetadata) ProtoMessage() {}

func (x *ServiceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetadata.ProtoReflect.Descriptor instead.
func (*ServiceMetadata) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceMetadata) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *ServiceMetadata) GetRepositoryUrl() string {
	if x != nil {
		return x.RepositoryUrl
	}
	return ""
}

func (x *ServiceMetadata) GetDocumentationUrl() string {
	if x != nil {
		return x.DocumentationUrl
	}
	return ""
}

func (x *ServiceMetadata) GetSupportContact() string {
	if x != nil {
		return x.SupportContact
	}
	return ""
}

func (x *ServiceMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ServiceCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersions   []string               `protobuf:"bytes,1,rep,name=api_versions,json=apiVersions,proto3" json:"api_versions,omitempty"` // Supported API versions
	Protocols     []string               `protobuf:"bytes,2,rep,name=protocols,proto3" json:"protocols,omitempty"`                        // Supported protocols (grpc, http)
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`                          // Enabled feature flags
	Dependencies  []*ServiceDependency   `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"`                  // Required services
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCapabilities) Reset() {
	*x = ServiceCapabilities{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCapabilities) ProtoMessage() {}

func (x *ServiceCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCapabilities.ProtoReflect.Descriptor instead.
func (*ServiceCapabilities) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{6}
}

func (x *ServiceCapabilities) GetApiVersions() []string {
	if x != nil {
		return x.ApiVersions
	}
	return nil
}

func (x *ServiceCapabilities) GetProtocols() []string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *ServiceCapabilities) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ServiceCapabilities) GetDependencies() []*ServiceDependency {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

type ServiceDependency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                // Dependency service name
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`                          // Required version (semver range)
	IsOptional    bool                   `protobuf:"varint,3,opt,name=is_optional,json=isOptional,proto3" json:"is_optional,omitempty"` // Whether dependency is optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDependency) Reset() {
	*x = ServiceDependency{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDependency) ProtoMessage() {}

func (x *ServiceDependency) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDependency.ProtoReflect.Descriptor instead.
func (*ServiceDependency) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceDependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceDependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceDependency) GetIsOptional() bool {
	if x != nil {
		return x.IsOptional
	}
	return false
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{8}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{9}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{10}
}

type LivenessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alive         bool                   `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{11}
}

func (x *LivenessResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *LivenessResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type HelloWorldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWorldRequest) Reset() {
	*x = HelloWorldRequest{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWorldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldRequest) ProtoMessage() {}

func (x *HelloWorldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldRequest.ProtoReflect.Descriptor instead.
func (*HelloWorldRequest) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{12}
}

func (x *HelloWorldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloWorldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloWorldResponse) Reset() {
	*x = HelloWorldResponse{}
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloWorldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloWorldResponse) ProtoMessage() {}

func (x *HelloWorldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloWorldResponse.ProtoReflect.Descriptor instead.
func (*HelloWorldResponse) Descriptor() ([]byte, []int) {
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP(), []int{13}
}

func (x *HelloWorldResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_payroll_services_payroll_service_proto_payroll_service_proto protoreflect.FileDescriptor

const file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDesc = "" +
	"\n" +
	"Eservices/payroll-services/payroll-service/proto/payroll_service.proto\x12\apayroll\"\x11\n" +
	"\x0fManifestRequest\"\xac\x02\n" +
	"\x10ManifestResponse\x124\n" +
	"\bidentity\x18\x01 \x01(\v2\x18.payroll.ServiceIdentityR\bidentity\x121\n" +
	"\n" +
	"build_info\x18\x02 \x01(\v2\x12.payroll.BuildInfoR\tbuildInfo\x127\n" +
	"\fruntime_info\x18\x03 \x01(\v2\x14.payroll.RuntimeInfoR\vruntimeInfo\x124\n" +
	"\bmetadata\x18\x04 \x01(\v2\x18.payroll.ServiceMetadataR\bmetadata\x12@\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1c.payroll.ServiceCapabilitiesR\fcapabilities\"\x82\x01\n" +
	"\x0fServiceIdentity\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x03 \x01(\tR\n" +
	"apiVersion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x98\x01\n" +
	"\tBuildInfo\x12\x1f\n" +
	"\vcommit_hash\x18\x01 \x01(\tR\n" +
	"commitHash\x12\x16\n" +
	"\x06branch\x18\x02 \x01(\tR\x06branch\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\x12\x18\n" +
	"\abuilder\x18\x04 \x01(\tR\abuilder\x12\x19\n" +
	"\bis_dirty\x18\x05 \x01(\bR\aisDirty\"\xca\x01\n" +
	"\vRuntimeInfo\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\n" +
	"started_at\x18\x03 \x01(\tR\tstartedAt\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12\x16\n" +
	"\x06region\x18\x05 \x01(\tR\x06region\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x03R\ruptimeSeconds\"\x9d\x02\n" +
	"\x0fServiceMetadata\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12%\n" +
	"\x0erepository_url\x18\x02 \x01(\tR\rrepositoryUrl\x12+\n" +
	"\x11documentation_url\x18\x03 \x01(\tR\x10documentationUrl\x12'\n" +
	"\x0fsupport_contact\x18\x04 \x01(\tR\x0esupportContact\x12<\n" +
	"\x06labels\x18\x05 \x03(\v2$.payroll.ServiceMetadata.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x01\n" +
	"\x13ServiceCapabilities\x12!\n" +
	"\fapi_versions\x18\x01 \x03(\tR\vapiVersions\x12\x1c\n" +
	"\tprotocols\x18\x02 \x03(\tR\tprotocols\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12>\n" +
	"\fdependencies\x18\x04 \x03(\v2\x1a.payroll.ServiceDependencyR\fdependencies\"b\n" +
	"\x11ServiceDependency\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1f\n" +
	"\vis_optional\x18\x03 \x01(\bR\n" +
	"isOptional\"\x0f\n" +
	"\rHealthRequest\"\xbe\x01\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12>\n" +
	"\adetails\x18\x03 \x03(\v2$.payroll.HealthResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x11\n" +
	"\x0fLivenessRequest\"O\n" +
	"\x10LivenessResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\"'\n" +
	"\x11HelloWorldRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x12HelloWorldResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2P\n" +
	"\bManifest\x12D\n" +
	"\vGetManifest\x12\x18.payroll.ManifestRequest\x1a\x19.payroll.ManifestResponse\"\x002\x8e\x01\n" +
	"\x06Health\x12>\n" +
	"\tGetHealth\x12\x16.payroll.HealthRequest\x1a\x17.payroll.HealthResponse\"\x00\x12D\n" +
	"\vGetLiveness\x12\x18.payroll.LivenessRequest\x1a\x19.payroll.LivenessResponse\"\x002Y\n" +
	"\x0ePayrollService\x12G\n" +
	"\n" +
	"HelloWorld\x12\x1a.payroll.HelloWorldRequest\x1a\x1b.payroll.HelloWorldResponse\"\x00B(Z&example.com/go-mono-repo/proto/payrollb\x06proto3"

var (
	file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescOnce sync.Once
	file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescData []byte
)

func file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescGZIP() []byte {
	file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescOnce.Do(func() {
		file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDesc), len(file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDesc)))
	})
	return file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDescData
}

var file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_services_payroll_services_payroll_service_proto_payroll_service_proto_goTypes = []any{
	(*ManifestRequest)(nil),     // 0: payroll.ManifestRequest
	(*ManifestResponse)(nil),    // 1: payroll.ManifestResponse
	(*ServiceIdentity)(nil),     // 2: payroll.ServiceIdentity
	(*BuildInfo)(nil),           // 3: payroll.BuildInfo
	(*RuntimeInfo)(nil),         // 4: payroll.RuntimeInfo
	(*ServiceMetadata)(nil),     // 5: payroll.ServiceMetadata
	(*ServiceCapabilities)(nil), // 6: payroll.ServiceCapabilities
	(*ServiceDependency)(nil),   // 7: payroll.ServiceDependency
	(*HealthRequest)(nil),       // 8: payroll.HealthRequest
	(*HealthResponse)(nil),      // 9: payroll.HealthResponse
	(*LivenessRequest)(nil),     // 10: payroll.LivenessRequest
	(*LivenessResponse)(nil),    // 11: payroll.LivenessResponse
	(*HelloWorldRequest)(nil),   // 12: payroll.HelloWorldRequest
	(*HelloWorldResponse)(nil),  // 13: payroll.HelloWorldResponse
	nil,                         // 14: payroll.ServiceMetadata.LabelsEntry
	nil,                         // 15: payroll.HealthResponse.DetailsEntry
}
var file_services_payroll_services_payroll_service_proto_payroll_service_proto_depIdxs = []int32{
	2,  // 0: payroll.ManifestResponse.identity:type_name -> payroll.ServiceIdentity
	3,  // 1: payroll.ManifestResponse.build_info:type_name -> payroll.BuildInfo
	4,  // 2: payroll.ManifestResponse.runtime_info:type_name -> payroll.RuntimeInfo
	5,  // 3: payroll.ManifestResponse.metadata:type_name -> payroll.ServiceMetadata
	6,  // 4: payroll.ManifestResponse.capabilities:type_name -> payroll.ServiceCapabilities
	14, // 5: payroll.ServiceMetadata.labels:type_name -> payroll.ServiceMetadata.LabelsEntry
	7,  // 6: payroll.ServiceCapabilities.dependencies:type_name -> payroll.ServiceDependency
	15, // 7: payroll.HealthResponse.details:type_name -> payroll.HealthResponse.DetailsEntry
	0,  // 8: payroll.Manifest.GetManifest:input_type -> payroll.ManifestRequest
	8,  // 9: payroll.Health.GetHealth:input_type -> payroll.HealthRequest
	10, // 10: payroll.Health.GetLiveness:input_type -> payroll.LivenessRequest
	12, // 11: payroll.PayrollService.HelloWorld:input_type -> payroll.HelloWorldRequest
	1,  // 12: payroll.Manifest.GetManifest:output_type -> payroll.ManifestResponse
	9,  // 13: payroll.Health.GetHealth:output_type -> payroll.HealthResponse
	11, // 14: payroll.Health.GetLiveness:output_type -> payroll.LivenessResponse
	13, // 15: payroll.PayrollService.HelloWorld:output_type -> payroll.HelloWorldResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_services_payroll_services_payroll_service_proto_payroll_service_proto_init() }
func file_services_payroll_services_payroll_service_proto_payroll_service_proto_init() {
	if File_services_payroll_services_payroll_service_proto_payroll_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDesc), len(file_services_payroll_services_payroll_service_proto_payroll_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_services_payroll_services_payroll_service_proto_payroll_service_proto_goTypes,
		DependencyIndexes: file_services_payroll_services_payroll_service_proto_payroll_service_proto_depIdxs,
		MessageInfos:      file_services_payroll_services_payroll_service_proto_payroll_service_proto_msgTypes,
	}.Build()
	File_services_payroll_services_payroll_service_proto_payroll_service_proto = out.File
	file_services_payroll_services_payroll_service_proto_payroll_service_proto_goTypes = nil
	file_services_payroll_services_payroll_service_proto_payroll_service_proto_depIdxs = nil
}
