// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: services/treasury-services/ledger-service/proto/ledger_service.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The empty request
type ManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestRequest) Reset() {
	*x = ManifestRequest{}
	mi := &file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestRequest) ProtoMessage() {}

func (x *ManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestRequest.ProtoReflect.Descriptor instead.
func (*ManifestRequest) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescGZIP(), []int{0}
}

// The response message containing the greetings
type ManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestResponse) Reset() {
	*x = ManifestResponse{}
	mi := &file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestResponse) ProtoMessage() {}

func (x *ManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestResponse.ProtoReflect.Descriptor instead.
func (*ManifestResponse) Descriptor() ([]byte, []int) {
	return file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescGZIP(), []int{1}
}

func (x *ManifestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_services_treasury_services_ledger_service_proto_ledger_service_proto protoreflect.FileDescriptor

const file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDesc = "" +
	"\n" +
	"Dservices/treasury-services/ledger-service/proto/ledger_service.proto\x12\x06ledger\"\x11\n" +
	"\x0fManifestRequest\",\n" +
	"\x10ManifestResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2N\n" +
	"\bManifest\x12B\n" +
	"\vGetManifest\x12\x17.ledger.ManifestRequest\x1a\x18.ledger.ManifestResponse\"\x00B'Z%example.com/go-mono-repo/proto/ledgerb\x06proto3"

var (
	file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescOnce sync.Once
	file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescData []byte
)

func file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescGZIP() []byte {
	file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescOnce.Do(func() {
		file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDesc), len(file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDesc)))
	})
	return file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDescData
}

var file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_treasury_services_ledger_service_proto_ledger_service_proto_goTypes = []any{
	(*ManifestRequest)(nil),  // 0: ledger.ManifestRequest
	(*ManifestResponse)(nil), // 1: ledger.ManifestResponse
}
var file_services_treasury_services_ledger_service_proto_ledger_service_proto_depIdxs = []int32{
	0, // 0: ledger.Manifest.GetManifest:input_type -> ledger.ManifestRequest
	1, // 1: ledger.Manifest.GetManifest:output_type -> ledger.ManifestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_treasury_services_ledger_service_proto_ledger_service_proto_init() }
func file_services_treasury_services_ledger_service_proto_ledger_service_proto_init() {
	if File_services_treasury_services_ledger_service_proto_ledger_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDesc), len(file_services_treasury_services_ledger_service_proto_ledger_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_treasury_services_ledger_service_proto_ledger_service_proto_goTypes,
		DependencyIndexes: file_services_treasury_services_ledger_service_proto_ledger_service_proto_depIdxs,
		MessageInfos:      file_services_treasury_services_ledger_service_proto_ledger_service_proto_msgTypes,
	}.Build()
	File_services_treasury_services_ledger_service_proto_ledger_service_proto = out.File
	file_services_treasury_services_ledger_service_proto_ledger_service_proto_goTypes = nil
	file_services_treasury_services_ledger_service_proto_ledger_service_proto_depIdxs = nil
}
